import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { cookies } from 'next/headers';
import { LOCALE_STORAGE_KEY, Locale } from '@/i18n/locales';
import { I18nNextProvider } from '@/i18n/client';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const lng =
    (cookies().get(LOCALE_STORAGE_KEY)?.value as Locale | undefined) ??
    Locale.En;

  return (
    <html lang={lng} suppressHydrationWarning>
      <I18nNextProvider lng={lng}>
        <body className={inter.className}>{children}</body>
      </I18nNextProvider>
    </html>
  );
}
